max_width = 100
tab_spaces = 2
indentation_style = "Auto"
newline_style = "Auto"
attr_value_brace_style = "AlwaysUnlessLit"
macro_names = [ "leptos::view", "view" ]
closing_tag_style = "Preserve"

[attr_values]
class = "Tailwind"